### ISSUE TITLE
Adding a newsletter signup widget

### ISSUE THREAD

**Issue by CMCDragonkai** [nitinthewiz/ghost-phantom#8]
How easily can I put up a newsletter signup widget? Where do you think would be best to put it in the layout of this theme?

**Comment by haydenbleasel** [comment]
Adding a newsletter signup widget shouldn't be hard at all - the vendor you're using (e.g. campaign monitor) should just give you a code snippet which can be thrown into the theme.

As for where to put it... If it's slim you can probably put it in the "navbar" area. Otherwise there's always the footer!

**Comment by CMCDragonkai** [comment]
I've got the newsletter signup widget, but I would like it to be center stage. What about if I put up a home page in the front above all the blog posts?

**Comment by haydenbleasel** [comment]
Yep you can do that pretty easily. Just open `index.hbs` and insert whatever you'd like just before `{{> excerpts}}`.

**Comment by CMCDragonkai** [comment]
Awesome thanks.

On 17/09/2014 10:53 AM, Hayden Bleasel wrote:

> Yep you can do that pretty easily. Just open |index.hbs| and insert 
> whatever you'd like just before |{{> excerpts}}|.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/haydenbleasel/phantom/issues/8#issuecomment-55835294.

## 

Founder of Polycademy & SnapSearch
http://polycademy.com
https://snapsearch.io
+61420925975
